import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import logo from './assets/image/logo.svg'

const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-col justify-center items-center mt-5">
          <section className={`flex justify-center items-center`}>
            <Image src={logo} alt="logo" className="w-24 h-auto" />
            <h1 className={`text-4xl text-center font-semibold drop-shadow-lg text-primary-purple`}>TODO LIST</h1>
          </section>
        </header>
        {children}
      </body>
    </html>
  );
}
